### ISSUE TITLE
fromGeojsonVt returns Uint8Array instead of Buffer

### ISSUE THREAD

**Issue by hannesj** [mapbox/vt-pbf#16]
In https://github.com/mapbox/vt-pbf/pull/15 pbf version 3 started returning `Uint8Array`s instead of `Buffer`s. This should have been a breaking major change, as it breaks usage eg. with node zlib, which expects a `Buffer`.

**Comment by anandthakker** [comment]
Thanks for the report @hannesj.  Re-published `2.1.3` as `3.0.0` and published patch version `2.1.4` with #15 reverted.
