### ISSUE TITLE
Does it encoding Polygon/MultiPoint correctly?

### ISSUE THREAD

**Issue by wsw0108** [mapbox/vt-pbf#17]
It seems that:
- No command `ClosePath` appeared in [code](https://github.com/mapbox/vt-pbf/blob/master/index.js#L111)
- No command `MoveTo` with count great than 1

**Comment by anandthakker** [comment]
Thanks @wsw0108 -- looking at the [spec](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4342-point-geometry-type), it appears the `ClosePath` command is indeed required:

> Each ExteriorRing and InteriorRing MUST consist of the following sequence:
>
> A MoveTo command with a command count of 1
> A LineTo command with a command count greater than 1
> A ClosePath command

@springmeyer @flippmoke do you have any context on why this hasn't caused us problems before now?  Maybe we were just lucky?

**Comment by wsw0108** [comment]
1. Although there was no ClosePath command, the concept of LinearRing which part of Polygon make it just woke.
2. MultiPoint is not supported, I will make a pr for this.
