### ISSUE TITLE
Vector tiles served from multipolygon type geojson are not rendered

### ISSUE THREAD

**Issue by gandhiamar2** [mapbox/vt-pbf#27]
My tile server is consuming NC zipcode polygon geojson (multipolygon type) using geojson-vt, vt-pbf and zlib. Mapbox-GL is not able to render these tiles and even not accepting responses and crashing the page. I concluded multipolygon array is the problem as rendering is successful when geometry coordinates are changed to a single array. 

<img width="1201" alt="screen shot 2017-12-08 at 12 58 04 pm" src="https://user-images.githubusercontent.com/22622144/33778938-da0c5342-dc18-11e7-82fe-81c229d70f78.png">

<img width="1201" alt="screen shot 2017-12-08 at 12 59 15 pm" src="https://user-images.githubusercontent.com/22622144/33778946-dfa90034-dc18-11e7-8cc8-266ebedd4acb.png">

However the multipolygon geojson works properly when processed as geojson at client. ( so I'm on the assumption that problem is not with  geojson-vt )

expected case: representation as a hole.
<img width="453" alt="screen shot 2017-12-08 at 1 00 25 pm" src="https://user-images.githubusercontent.com/22622144/33778954-e9e1ae8e-dc18-11e7-9f7a-3c1b109cb845.png">

geojson:
[dummyculprit.txt](https://github.com/mapbox/vt-pbf/files/1543479/dummyculprit.txt)

Please let me know if this is working as designed or is this a bug?

**Comment by jfirebaugh** [comment]
@gandhiamar2, could you please put together a minimal self-contained demonstration of the issue? The snippet of GeoJSON is not enough for us to diagnose the issue.

**Comment by gandhiamar2** [comment]
@jfirebaugh  I'm working on a local machine (tile server). It would be great if you can add this json as source for your tile server and give it a test. 
Please let me know if that's ok else I'll have to host this to make a working demo

**Comment by jfirebaugh** [comment]
The details of how you are converting it to a vector tile are important -- so, yes, please set up a full demo.

**Comment by gandhiamar2** [comment]
@jfirebaugh demo for the issue: [https://jsbin.com/husudij/edit?html,output](url)
u can change the source to https://mapbox-demo-cloned-gandhiamar2.c9users.io/ziplayer/dummyworking/{z}/{x}/{y}.pbf to see the difference
the server is hosted on cloud9  public repo [https://ide.c9.io/gandhiamar2/mapbox-demo-cloned#openfile-index.js](url)

**Comment by jfirebaugh** [comment]
I ran https://mapbox-demo-cloned-gandhiamar2.c9users.io/ziplayer/dummyworking/12/1139/1607.pbf through [vt2geojson](https://github.com/mapbox/vt2geojson) and got the following:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [ ... ]
        ]
      },
      "properties": {
        "id": "27403",
        "terrid": "27403"
      }
    }
  ]
}
```

So the multipolygon has been turned into a polygon somewhere in the VT encoding process. https://ide.c9.io/gandhiamar2/mapbox-demo-cloned#openfile-index.js wants a login or invasive Github oauth permissions, so I'm not able to see the code that way.

Just as a guess, is it possible you're running into https://github.com/mapbox/vt-pbf/issues/25?

**Comment by gandhiamar2** [comment]
nope I dont think so .. here is the code 
```  var  express = require("express"),
    app = express(),
    vtpbf = require("vt-pbf"),
    zlib = require("zlib"),
    fs = require("fs"),
    p = require("path"),
    geojsonVt = require("geojson-vt");
  
  
function getContentType(t) {
  var header = {};

  // CORS
  header["Access-Control-Allow-Origin"] = "*";
  header["Access-Control-Allow-Headers"] = "Origin, X-Requested-With, Content-Type, Accept";

  // Cache
  header["Cache-Control"] = "public, max-age=604800";

  // request specific headers
  if (t === "png") {
    header["Content-Type"] = "image/png";
  }
  if (t === "jpg") {
    header["Content-Type"] = "image/jpeg";
  }
  if (t === "pbf") {
    header["Content-Type"] = "application/x-protobuf";
    header["Content-Encoding"] = "gzip";
  }

  return header;
}    
    
// app.get('/ziplayer/:s/:z/:x/:y.:t', 
var ziplayer = function(req, res) {
  if(fs.existsSync(p.join(__dirname, req.params.s + '.json'))) {
    fs.readFile(p.join(__dirname, req.params.s + '.json'), 'utf8',function(err,GeoJSON) {
      if (err) {
        let header = {};
        header["Access-Control-Allow-Origin"] = "*";
        header["Access-Control-Allow-Headers"] = "Origin, X-Requested-With, Content-Type, Accept";
        header["Content-Type"] = "text/plain";
        res.set(header);
        res.status(204).send("'Tile rendering error: ' + err + '\n'");
      } else {
        var vtoptions =  {
            	maxZoom: 14,  // max zoom to preserve detail on; can't be higher than 24
            	tolerance: 3, // simplification tolerance (higher means simpler)
            	extent: 4096, // tile extent (both width and height)
            	buffer: 64,	  // tile buffer on each side
            	debug: 0   ,   // logging level (0 to disable, 1 or 2)
            	indexMaxZoom: 5,       // max zoom in the initial tile index
            	indexMaxPoints: 100000 // max number of points per tile in the index
            };
         var tileindex = geojsonVt(JSON.parse(GeoJSON));
         var tile = tileindex.getTile(parseInt(req.params.z, 10), parseInt(req.params.x, 10), parseInt(req.params.y));
        if(!tile){
          let header = {};
          header["Access-Control-Allow-Origin"] = "*";
          header["Access-Control-Allow-Headers"] = "Origin, X-Requested-With, Content-Type, Accept";
          header["Content-Type"] = "text/plain";
          res.set(header);
          res.status(204).send("im out ");

           console.log("reqZ:"+req.params.z + "  reqX:"+req.params.x+"    reqY:"+req.params.y + "no tile generated");
        }
       else if(tile){
           console.log("reqZ:"+req.params.z + "  reqX:"+req.params.x+"    reqY:"+req.params.y +" features:"+ tile.features.length+ "  tilex:"+ tile.x+"  tiley:"+tile.y+"   tileZ2:"+tile.z2+" tileminX:"+tile.minX+"  tileminY:"+tile.minY+"  tilemaxX:"+tile.maxX+"  tilemaxY:"+tile.maxY)
           var layer = new vtpbf.GeoJSONWrapper(tile.features);
            layer.name = 'geojsonLayer';
            layer.version = 2;
            var buff = vtpbf.fromGeojsonVt({
                geojsonLayer: tile
            });
            var buff2 = vtpbf.fromVectorTileJs({layers: {
              geojsonLayer: layer
            }});
            zlib.gzip(buff2, function(err, pbf) {
              if(!err){
                 res.set(getContentType(req.params.t));
                 res.send(pbf);
              }else{
                 res.status(404).send(err);
              }
             });
         }
      }
    });
  }
    else{
      console.log("error opening file");
    }
};
    
// app.listen(process.env.PORT || 3000, process.env.IP || "0.0.0.0");

module.exports= ziplayer;```

**Comment by gandhiamar2** [comment]
please see through network tab in the demo.. the renderer stopped working at some point in  a higher zoom level and it will not accept or make new requests, in some time will crash the app

**Comment by gandhiamarnadh** [comment]
@jfirebaugh  there are two json files
two arrays are merged in one ...  so this returning as polygon is not surprising
https://mapbox-demo-cloned-gandhiamar2.c9users.io/ziplayer/dummyworking/{z}/{x}/{y}.pbf 

original array (you should test with this one)
https://mapbox-demo-cloned-gandhiamar2.c9users.io/ziplayer/dummyculprit/{z}/{x}/{y}.pbf

**Comment by gandhiamarnadh** [comment]
@jfirebaugh it's working fine when vector tiles generated using mapnik

**Comment by tobinbradley** [comment]
At risk of making the highly unhelpful "me too" post...me too. I'm not sure it's a multipolygon issue though.

I'm doing something similar - Postgis recordset (wkb) to GeoJSON to VT (geojson-vt) to protobuf (vt-pbf). vt-pbf 2.1.4 works fine for my building polygons with geometry stored as multipolygon.  3.0.1 does as @gandhiamar2 describes - GL JS doesn't render anything and eventually Chrome murders the page. 

I tried making a new Postgres table with the geometry as polygon via:

```sql
CREATE TABLE buildings_poly AS 
    SELECT id, (ST_DUMP(geom)).geom::geometry(Polygon,2264) AS geom FROM buildings
```

No dice here either. Switch from vt-pbf 3.0.1 to 2.1.4 and GL JS starts rendering features again, for both the polygon and multipolygon geometry types. 

I realize other than pointing out the previous release works this isn't terribly helpful. If there's anything else I can provide let me know.

**Comment by exe-dealer** [comment]
It seems that all polygons with holes are breaks vt decoder burning cpu and eat memory until die. Here is minimal representation https://github.com/exe-dealer/geojson-vt-issue

this code blows cpu and mem and never prints the decoded tile

```js
const fs = require('fs');
const vtpbf = require('vt-pbf');
const vt2geojson = require('vt2geojson');

const buff = Buffer.from(vtpbf.fromGeojsonVt({
  somelayer: {
    features: [
      {
        "geometry": [
          [
              [0,0],
              [10, 0],
              [10,10],
              [0, 10],
              [0,0]
          ],
          [
              [2,2],
              [4,2],
              [4,4],
              [2,4],
              [2,2]
          ]
        ],
        "type": 3
      }
    ]
  }
}, { version: 2 }));


fs.writeFileSync('/tmp/badvt', buff);

vt2geojson({
  uri: '/tmp/badvt',
  z: 0,
  x: 0,
  y: 0,
}, console.log)
```
