### ISSUE TITLE
Error 'ERR_CONTENT_DECODING_FAILED' when serving the result

### ISSUE THREAD

**Issue by knownasilya** [mapbox/vt-pbf#34]
Not sure what I'm doing wrong in this scenario.

```js
  var vtpbf = require('vt-pbf')
  var geojsonVt = require('geojson-vt')
  var tileindex = geojsonVt(geojson)
  var tile = tileindex.getTile(Number(z), Number(x), Number(y))
  var vt = vtpbf.fromGeojsonVt({ 'geojsonLayer': tile });

  res.set({
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept',
    'Content-Type': 'application/x-protobuf',
    'Content-Encoding': 'gzip'
  });

  res.send(vt);
```

Can be seen here: https://geojson-vt-test-mlrzlkgssx.now.sh/
Full code here: https://geojson-vt-test-mlrzlkgssx.now.sh/_src

**Comment by knownasilya** [comment]
If I only pass the `'Content-Type': 'application/x-protobuf'` header, then it loads, but I get: `Uncaught Error: Unimplemented type: 3` 

![screen shot 2018-10-24 at 5 46 12 pm](https://user-images.githubusercontent.com/34726/47463623-bd9bf580-d7b4-11e8-893b-9ddfd3074b21.png)

**Comment by bezany** [comment]
I think need use `zlib.gzip` for compress of response. I use code like  [here](https://github.com/mapbox/vt-pbf/issues/27#issuecomment-350408819) and it is works.

**Comment by knownasilya** [comment]
That actually worked, thanks @bezany!
