### ISSUE TITLE
Flatten nested properties

### ISSUE THREAD

**Issue by hannesj** [mapbox/vt-pbf#5]
Currently if you have an object as a property (e.g. from a GeopJSON-file), it will be stored as `[object Object]` in the protobuf. It should probably be flattened, e.g. using the dot-notation so that `{"name": {"en": "Place"}}` would become `{"name.en": "Place"}`, before storing it.

**Comment by anandthakker** [comment]
Looks like Mapnik stringifies such values ([reference](https://www.mapbox.com/vector-tiles/specification/#how-to-encode-attributes-that-arent-strings-or-numbers)

**Comment by hannesj** [comment]
That would probably be a good solution in order to be compatible. Did a PR for this (#6)
