### ISSUE TITLE
Enable setting feature ID

### ISSUE THREAD

**Issue by hannesj** [mapbox/vt-pbf#7]
The VT specification allows features to have an id specified, and geojson-vt passes those trought after mapbox/geojson-vt#70 was merged. Vt-pbf should probably write those ids to the vector tiles.

**Comment by anandthakker** [comment]
Agreed!

**Comment by hannesj** [comment]
Should I do a PR (this time including tests) or are you on to this?

**Comment by anandthakker** [comment]
A PR with unit tests would be much appreciated!

**Comment by hannesj** [comment]
@anandthakker done as #8 

Could you carve out a new release after that one is merged?
